name: Sweetman Design
favicon: null
layout_spectrum: 0.8716749493032694
typography_spectrum: 0.45525071886368096
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.32468459592200816
  lightness: 0.04279867885634303
  saturation: 0.5145090732257813
  rhythmicContrast: 0.3719431268982589
purpose: []
