name: Sweetman Design
favicon: null
layout_spectrum: 0.14727
typography_spectrum: 0.66226
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#050505'
    - '#2a2b38'
    - '#83848a'
    - '#cbccd4'
  brandStrength: 0.6875
  lightness: 0.75
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
