name: Sweetman Design
favicon: null
layout_spectrum: 0.8716749493032694
typography_spectrum: 0.59206
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000309'
    - '#fefefe'
    - '#7ed4eb'
    - '#3f77ad'
    - '#f12868'
  brandStrength: 0.75
  lightness: 0.6875
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
