favicon: null
name: Sweetman Design
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.3125
  brandStrength: 0.6875
  lightness: 0.6379929
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#99908c'
    - '#4c433c'
    - '#790005'
  rhythmicContrast: 0.6827957
typography_spectrum: 0.5770609
layout_spectrum: 0.2096774
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
